package com.appleframework.id;

import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.redis.core.RedisTemplate;

import com.appleframework.id.exception.IdException;

/**
 * This id generator utilizes Redis (http://redis.io/) to generate serial IDs.
 * 
 * <p>
 * Persistency: IDs generated by this id-generator are persistent (assuming the
 * Redis backend runs in persistent mode).
 * </p>
 * 
 * @author cruise.xu <xushaomin@foxmail.com>
 * @since 0.1.0
 */
public class RedisIdGenerator extends SerialIdGenerator implements IdentityGenerator {

	private static Logger logger = LoggerFactory.getLogger(RedisIdGenerator.class);

    /**
     * Helper method to obtain {@link RedisIdGenerator}.
     * 
     * @param redisTemplate
     * @return
     */
	public static RedisIdGenerator getInstance(final RedisTemplate<String, Long> redisTemplate) {
		StringBuilder key = new StringBuilder();
		key.append(redisTemplate.hashCode());
		try {
			RedisIdGenerator idGen = (RedisIdGenerator) idGenerators.get(key.toString(),
					new Callable<SerialIdGenerator>() {
						@Override
						public SerialIdGenerator call() throws Exception {
							RedisIdGenerator idGen = new RedisIdGenerator();
							idGen.setRedisTemplate(redisTemplate).init();
							return idGen;
						}
					});
			return idGen;
		} catch (ExecutionException e) {
			logger.warn(e.getMessage(), e);
			return null;
		}
	}

    private RedisTemplate<String, Long> redisTemplate;

    public RedisTemplate<String, Long> getRedisTemplate() {
		return redisTemplate;
	}
    
	public RedisIdGenerator setRedisTemplate(RedisTemplate<String, Long> redisTemplate) {
		this.redisTemplate = redisTemplate;
		return this;
	}
	
    /**
     * {@inheritDoc}
     */
    @Override
    public RedisIdGenerator init() {
        super.init();
        return this;
    }

    public void destroy() {
        super.destroy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
	public long nextId(final String namespace) {
		if (redisTemplate != null) {
			try {
				return redisTemplate.opsForValue().increment(namespace, 1);
			} catch (Exception e) {
				throw new IdException.OperationFailedException(e);
			}
		} else {
			return -1;
		}
	}

    /**
     * {@inheritDoc}
     */
    @Override
    public long currentId(final String namespace) {
    	if (redisTemplate != null) {
			try {
				return redisTemplate.opsForValue().get(namespace);
			} catch (Exception e) {
				throw new IdException.OperationFailedException(e);
			}
		} else {
			return -1;
		}
    }

    /**
     * {@inheritDoc}
     * 
     * @since 0.4.0
     */
    @Override
    public boolean setValue(final String namespace, final long value) {
        if (redisTemplate != null) {
            try {
            	redisTemplate.opsForValue().set(namespace, value);
                return true;
            } catch (Exception e) {
                throw new IdException.OperationFailedException(e);
            }
        } else {
            return false;
        }
    }
}